"""Initial CloudScope Lite schema."""
from alembic import op
import sqlalchemy as sa
revision="20260906_0001";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
    op.create_table("users",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.String(100),nullable=False),sa.Column("email",sa.String(255),nullable=False),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("email"));op.create_index("ix_users_email","users",["email"])
    op.create_table("projects",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("project_name",sa.String(120),nullable=False),sa.Column("aws_region",sa.String(30),nullable=False),sa.Column("monthly_budget",sa.Float(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("analyses",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id"),nullable=False),sa.Column("terraform_filename",sa.String(255),nullable=False),sa.Column("workload_scenario",sa.String(20),nullable=False),sa.Column("estimated_monthly_cost",sa.Float(),nullable=False),sa.Column("budget_status",sa.String(30),nullable=False),sa.Column("pricing_effective_date",sa.String(20),nullable=False),sa.Column("report_json",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("resource_estimates",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("analysis_id",sa.Integer(),sa.ForeignKey("analyses.id"),nullable=False),sa.Column("resource_type",sa.String(60),nullable=False),sa.Column("resource_name",sa.String(120),nullable=False),sa.Column("configuration_json",sa.Text(),nullable=False),sa.Column("pricing_json",sa.Text(),nullable=False),sa.Column("estimated_monthly_cost",sa.Float(),nullable=False),sa.Column("warnings_json",sa.Text(),nullable=False))
    op.create_table("recommendations",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("analysis_id",sa.Integer(),sa.ForeignKey("analyses.id"),nullable=False),sa.Column("resource_name",sa.String(120),nullable=False),sa.Column("recommendation_type",sa.String(60),nullable=False),sa.Column("recommendation_text",sa.Text(),nullable=False),sa.Column("current_cost",sa.Float()),sa.Column("alternative_cost",sa.Float()),sa.Column("estimated_savings",sa.Float()),sa.Column("confidence_level",sa.String(20),nullable=False))
    op.create_table("historical_costs",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id"),nullable=False),sa.Column("cost_date",sa.String(20),nullable=False),sa.Column("actual_cost",sa.Float(),nullable=False),sa.Column("is_anomaly",sa.Boolean(),nullable=False),sa.Column("anomaly_method",sa.String(30)))
def downgrade():
    for table in ("historical_costs","recommendations","resource_estimates","analyses","projects"): op.drop_table(table)
    op.drop_index("ix_users_email",table_name="users");op.drop_table("users")
